title: 聖誕頌歌 - 晚安．月亮
description: 聖誕頌歌 - 晚安．月亮
time: Wed, 04 Sep 2024 00:14:12 +0000
items:
  - title: 00. 聖誕頌歌
    size: 1095344
    duration: 108
  - title: 01. 吝嗇刻薄的史古基先生
    size: 4621724
    duration: 471
  - title: 02. 寒冷的聖誕夜
    size: 5146568
    duration: 519
  - title: 03. 馬里的鬼魂
    size: 4979886
    duration: 505
  - title: 04. 馬里的懺悔
    size: 5226761
    duration: 537
  - title: 05. 第一個精靈
    size: 5309056
    duration: 534
  - title: 06. 童年的回憶
    size: 4942069
    duration: 495
  - title: 07. 聖誕節的回憶
    size: 5218316
    duration: 506
  - title: 08. 分手的回憶
    size: 4312051
    duration: 429
  - title: 09. 擦身而過的幸福
    size: 5322401
    duration: 535
  - title: 10. 第二個精靈
    size: 5347776
    duration: 538
  - title: 11. 貧窮卻溫馨的聖誕節回憶
    size: 4637705
    duration: 468
  - title: 12. 知足感恩的一家人
    size: 5163001
    duration: 525
  - title: 13. 海上的派對
    size: 4300005
    duration: 432
  - title: 14. 「無知」與「貧乏」
    size: 4069397
    duration: 415
  - title: 15. 第三個精靈
    size: 4080853
    duration: 423
  - title: 16. 詭異的拍賣會
    size: 5445702
    duration: 553
  - title: 17. 淒涼的史古基
    size: 5285228
    duration: 537
  - title: 18. 誰的墳墓？
    size: 5158029
    duration: 528
  - title: 19. 重獲新生
    size: 5026963
    duration: 497
  - title: 20. 聖誕快樂
    size: 4810689
    duration: 476
